# -*- coding: utf-8 -*-
"""GNN_v3_clevland.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a8EUA8Ea84fQ_ywpDSmi6yA2XjQDlkhi
"""

!pip install torch-geometric -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

import torch
import torch.nn.functional as F
from torch_geometric.data import Data
from torch_geometric.nn import (
    GCNConv,
    global_mean_pool  #There are 14 features(nodes) and all give an output embedding..I have pooled it in single output(final prediciton)
)

"""**LOAD DATASET**"""

df = pd.read_csv('Heart_disease_cleveland_new.csv')

"""**PREPROCESSING**"""

# num_cols = df.drop(columns=["target"]).select_dtypes(include=['int64','float64']).columns

# Q1 = df[num_cols].quantile(0.25)
# Q3 = df[num_cols].quantile(0.75)
# IQR = Q3 - Q1

# df = df[~((df[num_cols] < (Q1 - 1.5 * IQR)) |
#           (df[num_cols] > (Q3 + 1.5 * IQR))).any(axis=1)]

# print("After Outlier Removal:", df.shape)

X = df.drop(columns=['target'])
y = df['target']



# #Min-max normalization
binary_cols = [
    'sex',
    'cp',
    'fbs',
    'restecg',
    'slope',
    'ca',
    'thal',
    'exang'
]

numeric_cols = [
    col for col in X.columns
    if col not in binary_cols
]

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y,
    test_size=0.30,
    stratify=y,
    random_state=42
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp,
    test_size=0.50,
    stratify=y_temp,
    random_state=42
)

scaler = MinMaxScaler()

X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])

X_val[numeric_cols] = scaler.transform(X_val[numeric_cols])

X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

# Correlation matrix — computed on SCALED training data only (Bug #3 fix: no leakage)
import seaborn as sns

FEATURES = [
    'age', 'sex', 'cp', 'trestbps', 'chol',
    'fbs', 'restecg', 'thalach', 'exang',
    'oldpeak', 'slope', 'ca', 'thal'
]

# Use X_train (already scaled by MinMaxScaler above) — NOT the full raw dataset
corr_matrix = X_train[FEATURES].corr()

print("corr_matrix shape:", corr_matrix.shape)   # should be (13, 13)
print("Columns:", corr_matrix.columns.tolist())
plt.figure(figsize=(12,8))
sns.heatmap(corr_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Matrix (Scaled Training Data)")
plt.show()

# Bug #2 fix: The duplicate train_test_split block below has been REMOVED.
# It was overwriting the stratified, scaled splits above with raw unscaled data,
# causing the model to train on un-normalised features and collapse to a constant.
# The correct 70/15/15 stratified split with MinMax scaling already exists above.
print("Train:", len(X_train))
print("Validation:", len(X_val))
print("Test:", len(X_test))

"""**CREATING GRAPH USING NETWORKX**"""

import pandas as pd
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# ─────────────────────────────────────────────────────────────
# Load data
# ─────────────────────────────────────────────────────────────
FEATURES = [
    'age', 'sex', 'cp', 'trestbps', 'chol',
    'fbs', 'restecg', 'thalach', 'exang',
    'oldpeak', 'slope', 'ca', 'thal'
]

X  = X_train[FEATURES]
corr_matrix = X.corr()   # 13x13 including age

print(f"corr_matrix shape: {corr_matrix.shape}")
print(f"columns: {corr_matrix.columns.tolist()}")

# ─────────────────────────────────────────────────────────────
# Build primary (thresholded) graph
# ─────────────────────────────────────────────────────────────
threshold = 0.15

G = nx.Graph()
for feature in FEATURES:
    G.add_node(feature)

for i in range(len(corr_matrix.columns)):
    for j in range(i + 1, len(corr_matrix.columns)):
        corr_value = corr_matrix.iloc[i, j]
        if abs(corr_value) >= threshold:
            G.add_edge(
                corr_matrix.columns[i],
                corr_matrix.columns[j],
                weight=corr_value,   # signed, for display only
                primary=True
            )

# ─────────────────────────────────────────────────────────────
# MST over the COMPLETE graph, distance = 1 - |corr|
# (guarantees a fully connected backbone; only missing pairs
#  from the primary graph get added as bridge edges)
# ─────────────────────────────────────────────────────────────
G_complete = nx.Graph()
for i in range(len(FEATURES)):
    for j in range(i + 1, len(FEATURES)):
        G_complete.add_edge(
            FEATURES[i], FEATURES[j],
            weight=1 - abs(corr_matrix.iloc[i, j])
        )

mst = nx.minimum_spanning_tree(G_complete)
for u, v in mst.edges():
    if not G.has_edge(u, v):
        G.add_edge(u, v, weight=corr_matrix.loc[u, v], primary=False)

print(f"\nNodes: {G.number_of_nodes()}")
print(f"Edges: {G.number_of_edges()}")
print(f"Connected: {nx.is_connected(G)}")

# ─────────────────────────────────────────────────────────────
# FIX: Fiedler value must come from a NON-NEGATIVE weight graph.
# Signed correlation weights break positive-semidefiniteness of
# the Laplacian and can produce an impossible negative lambda_2.
# Use |correlation| purely for this calculation; the plot itself
# still uses signed weight for edge color / width.
# ─────────────────────────────────────────────────────────────
G_pos = G.copy()
for u, v, d in G_pos.edges(data=True):
    d['weight'] = abs(d['weight'])

L           = nx.laplacian_matrix(G_pos, weight='weight').toarray()
eigenvalues = np.sort(np.linalg.eigvalsh(L))
fiedler     = eigenvalues[1]
print(f"Fiedler λ₂ (fixed, non-negative weights): {fiedler:.4f}")

# sanity check: should never be negative
assert fiedler >= -1e-9, "Fiedler value still negative — Laplacian weights not fixed correctly"

# ─────────────────────────────────────────────────────────────
# Node positions (all 13 nodes)
# ─────────────────────────────────────────────────────────────
pos = {
    'age':      ( 0.0,  3.0),
    'sex':      (-2.5,  2.5),
    'cp':       (-1.2,  1.4),
    'exang':    ( 1.2,  1.4),
    'trestbps': (-2.2,  0.0),
    'thalach':  ( 2.2,  0.0),
    'chol':     (-1.2, -1.2),
    'fbs':      ( 1.2, -1.2),
    'restecg':  (-2.2, -2.6),
    'oldpeak':  ( 0.0, -2.6),
    'slope':    ( 2.2, -2.6),
    'ca':       (-1.0, -4.0),
    'thal':     ( 1.0, -4.0),
}

missing = [n for n in G.nodes() if n not in pos]
if missing:
    print(f"WARNING: Missing positions for: {missing}")
else:
    print("All nodes have positions ✓")

# ─────────────────────────────────────────────────────────────
# Clinical color groups
# ─────────────────────────────────────────────────────────────
groups = {
    'Demographic':    ['age', 'sex'],
    'Chest Pain':     ['cp', 'exang'],
    'Vital Signs':    ['trestbps', 'thalach'],
    'Laboratory':     ['chol', 'fbs'],
    'ECG & Exercise': ['restecg', 'oldpeak', 'slope'],
    'Imaging':        ['ca', 'thal'],
}
group_colors = {
    'Demographic':    '#3498DB',
    'Chest Pain':     '#E74C3C',
    'Vital Signs':    '#2ECC71',
    'Laboratory':     '#F39C12',
    'ECG & Exercise': '#9B59B6',
    'Imaging':        '#1ABC9C',
}
node_color_map = {}
for grp, nodes in groups.items():
    for n in nodes:
        node_color_map[n] = group_colors[grp]

# ─────────────────────────────────────────────────────────────
# Visualization
# ─────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(20, 9))

ax = axes[0]

primary_edges = [(u, v) for u, v, d in G.edges(data=True) if d.get('primary', False)]
bridge_edges  = [(u, v) for u, v, d in G.edges(data=True) if not d.get('primary', False)]

primary_widths = [abs(G[u][v]['weight']) * 7 for u, v in primary_edges]
primary_colors = ['#C0392B' if G[u][v]['weight'] > 0 else '#2980B9'
                   for u, v in primary_edges]
bridge_widths  = [abs(G[u][v]['weight']) * 3 for u, v in bridge_edges]

nx.draw_networkx_edges(G, pos, edgelist=primary_edges,
                        width=primary_widths, edge_color=primary_colors,
                        alpha=0.85, ax=ax)
nx.draw_networkx_edges(G, pos, edgelist=bridge_edges,
                        width=bridge_widths, edge_color='#95A5A6',
                        alpha=0.6, style='dashed', ax=ax)

node_sizes  = [800 + G.degree(n) * 220 for n in G.nodes()]
node_colors = [node_color_map[n] for n in G.nodes()]

nx.draw_networkx_nodes(G, pos, node_size=node_sizes,
                        node_color=node_colors, alpha=0.95, ax=ax)

labels = {
    'age':      'Age',
    'sex':      'Sex',
    'cp':       'Chest\nPain',
    'trestbps': 'Resting\nBP',
    'chol':     'Cholesterol',
    'fbs':      'FBS',
    'restecg':  'Rest\nECG',
    'thalach':  'Max\nHR',
    'exang':    'Exercise\nAngina',
    'oldpeak':  'Oldpeak',
    'slope':    'Slope',
    'ca':       'CA',
    'thal':     'Thal',
}
nx.draw_networkx_labels(G, pos, labels=labels,
                         font_size=8, font_weight='bold',
                         font_color='white', ax=ax)

edge_labels = {
    (u, v): f"{G[u][v]['weight']:.2f}"
    for u, v, d in G.edges(data=True)
    if d.get('primary', False) and abs(d['weight']) >= 0.30
}
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels,
                              font_size=7, font_color='black', ax=ax)

legend_elements = [
    mpatches.Patch(color=c, label=g) for g, c in group_colors.items()
] + [
    mpatches.Patch(color='#C0392B', label='Positive Correlation'),
    mpatches.Patch(color='#2980B9', label='Negative Correlation'),
    mpatches.Patch(color='#95A5A6', label='MST Bridge Edge'),
]
ax.legend(handles=legend_elements, fontsize=8,
          loc='lower left', framealpha=0.95)
ax.set_title(
    f"Feature Correlation Graph\n"
    f"Threshold={threshold} | {G.number_of_nodes()} Nodes | "
    f"{G.number_of_edges()} Edges | Fiedler={fiedler:.4f}",
    fontsize=12, fontweight='bold')
ax.axis('off')

# ── RIGHT: Degree distribution ──
ax2          = axes[1]
sorted_nodes = sorted(G.nodes(), key=lambda x: G.degree(x), reverse=True)
degrees      = [G.degree(n) for n in sorted_nodes]
colors       = [node_color_map[n] for n in sorted_nodes]

ax2.barh(sorted_nodes, degrees, color=colors, edgecolor='white')
ax2.invert_yaxis()
ax2.set_xlabel('Degree')
ax2.set_title('Node Degree Distribution', fontsize=12, fontweight='bold')
mean_deg = np.mean(degrees)
ax2.axvline(mean_deg, color='gray', linestyle='--',
            label=f'Mean = {mean_deg:.2f}')
for i, val in enumerate(degrees):
    ax2.text(val + 0.05, i, str(val), va='center',
              fontsize=9, fontweight='bold')
ax2.legend()
ax2.spines['top'].set_visible(False)
ax2.spines['right'].set_visible(False)

plt.tight_layout()
plt.savefig('heart_feature_graph.png', dpi=300, bbox_inches='tight')
plt.show()
print("\nSaved: heart_feature_graph.png")

node_mapping = {
    node: idx
    for idx, node in enumerate(G.nodes())
}

edge_list = []

for edge in G.edges():

    source = node_mapping[edge[0]]
    target = node_mapping[edge[1]]

    edge_list.append([source, target])
    edge_list.append([target, source])



edge_index = torch.tensor(edge_list,dtype=torch.long).t().contiguous()

def create_graphs(X_data, y_data):

    graph_list = []
    for idx in range(len(X_data)):


        # Bug #1 fix: always select columns in FEATURES order so that
        # node i in the graph corresponds exactly to FEATURES[i].
        # Using .values directly on the full DataFrame gives pandas' original
        # column order, which may not match node_mapping — causing silent
        # feature-to-node misalignment and destroying all gradient signal.
        patient_features = X_data[FEATURES].iloc[idx].values

        x = torch.tensor(patient_features, dtype=torch.float).view(-1, 1)
        y = torch.tensor([float(y_data.iloc[idx])],dtype=torch.float)


        graph = Data(
            x=x,
            edge_index=edge_index,
            y=y
        )

        graph_list.append(graph)

    return graph_list


# Graph lists are created fresh inside each CV fold below.
# A single sample graph is built here only for structural inspection.
_sample_graphs = create_graphs(
    X_train.reset_index(drop=True),
    y_train.reset_index(drop=True)
)
train_graphs = _sample_graphs   # alias so GCN class definition below compiles
val_graphs   = _sample_graphs   # placeholder — overwritten per fold
test_graphs  = _sample_graphs   # placeholder — overwritten per fold
print("Sample graph shape check:", _sample_graphs[0])

"""**Graph Neural Network Training**"""

class GCN(torch.nn.Module):

    def __init__(self, input_channels, hidden_channels):

        super().__init__()

        self.conv1 = GCNConv(input_channels,hidden_channels)
        self.conv2 = GCNConv(hidden_channels,hidden_channels)
        self.linear = torch.nn.Linear(hidden_channels,1)

    def forward(self, data):

        x = data.x
        edge_index = data.edge_index

        x = self.conv1(x, edge_index)
        x = F.relu(x)



        x = F.dropout(
            x,
            p=0.30,
            training=self.training
        )


        x = self.conv2(x, edge_index)

        x = F.relu(x)


        # Bug #4 fix: use data.batch when graphs are batched via DataLoader
        # (batch_size > 1); fall back to all-zeros only for single-graph inference.
        # Hardcoding zeros silently pools all patients' nodes into one embedding
        # when using a DataLoader with batch_size > 1.
        batch = (data.batch if (hasattr(data, 'batch') and data.batch is not None)
                 else torch.zeros(x.size(0), dtype=torch.long, device=x.device))

        # Graph Pooling because [14,hidden_layer] from 14 nodes(feature) make it [1,hidden_layer]

        x = global_mean_pool(x,batch)



        x = self.linear(x)

        x = torch.sigmoid(x)

        return x.view(-1)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix, matthews_corrcoef
)
import warnings
warnings.filterwarnings('ignore')

# ── Shared metric helper (used by CV loop and baselines) ──
def compute_metrics(y_true, y_pred, y_prob):
    cm = confusion_matrix(y_true, y_pred)
    TP = cm[1,1]; FN = cm[1,0]; TN = cm[0,0]; FP = cm[0,1]
    return {
        'Accuracy':    round(accuracy_score(y_true, y_pred), 4),
        'Precision':   round(precision_score(y_true, y_pred, zero_division=0), 4),
        'Recall':      round(recall_score(y_true, y_pred, zero_division=0), 4),
        'F1 Score':    round(f1_score(y_true, y_pred, zero_division=0), 4),
        'ROC-AUC':     round(roc_auc_score(y_true, y_prob), 4),
        'MCC':         round(matthews_corrcoef(y_true, y_pred), 4),
        'Specificity': round(TN/(TN+FP), 4) if (TN+FP) > 0 else 0,
        'FPR':         round(FP/(FP+TN), 4) if (FP+TN) > 0 else 0,
        'FNR':         round(FN/(FN+TP), 4) if (FN+TP) > 0 else 0,
    }

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold

# ─────────────────────────────────────────────────────────────
# BASELINE ML MODEL COMPARISON
# Paste AFTER your GNN test evaluation cell
# Requires: all_labels, all_predictions, all_probabilities
# ─────────────────────────────────────────────────────────────

FEATURES = [
    'age', 'sex', 'cp', 'trestbps', 'chol',
    'fbs', 'restecg', 'thalach', 'exang',
    'oldpeak', 'slope', 'ca', 'thal'
]



df       = pd.read_csv('Heart_disease_cleveland_new.csv')
X        = df[FEATURES].values
y        = df['target'].values
scaler   = StandardScaler()
X_scaled = scaler.fit_transform(X)

# ── Helper ──
def compute_metrics(y_true, y_pred, y_prob):
    cm = confusion_matrix(y_true, y_pred)
    TP = cm[1,1]; FN = cm[1,0]
    TN = cm[0,0]; FP = cm[0,1]
    return {
        'Accuracy':    round(accuracy_score(y_true, y_pred), 4),
        'Precision':   round(precision_score(y_true, y_pred, zero_division=0), 4),
        'Recall':      round(recall_score(y_true, y_pred, zero_division=0), 4),
        'F1 Score':    round(f1_score(y_true, y_pred, zero_division=0), 4),
        'ROC-AUC':     round(roc_auc_score(y_true, y_prob), 4),
        'MCC':         round(matthews_corrcoef(y_true, y_pred), 4),
        'Specificity': round(TN / (TN + FP), 4) if (TN + FP) > 0 else 0,
        'FNR':         round(FN / (FN + TP), 4) if (FN + TP) > 0 else 0,
        'FPR':         round(FP / (FP + TN), 4) if (FP + TN) > 0 else 0,
    }

# ── Baseline ML models ──
ml_models = {
    'Logistic Regression': LogisticRegression(
        max_iter=1000, class_weight='balanced', random_state=42),
    'Random Forest': RandomForestClassifier(
        n_estimators=100, class_weight='balanced', random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(
        n_estimators=100, random_state=42),
    'MLP': MLPClassifier(
        hidden_layer_sizes=(64, 32), max_iter=200, random_state=42),
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

print("=" * 65)
print("  BASELINE ML MODEL COMPARISON (5-Fold Cross Validation)")
print("=" * 65)

baseline_results = {}

for name, clf in ml_models.items():
    print(f"\nTraining {name}...")
    y_pred = cross_val_predict(clf, X_scaled, y, cv=cv, method='predict')
    y_prob = cross_val_predict(clf, X_scaled, y, cv=cv, method='predict_proba')[:, 1]
    metrics = compute_metrics(y, y_pred, y_prob)
    baseline_results[name] = metrics
    print(f"  Accuracy : {metrics['Accuracy']:.4f}")
    print(f"  Recall   : {metrics['Recall']:.4f}")
    print(f"  F1 Score : {metrics['F1 Score']:.4f}")
    print(f"  ROC-AUC  : {metrics['ROC-AUC']:.4f}")
    print(f"  MCC      : {metrics['MCC']:.4f}")

# ── GCN: computed from your existing test variables ──
baseline_results['GCN (Ours)'] = compute_metrics(
    all_labels,
    all_predictions,
    all_probabilities
)

# ── Full comparison table ──
print("\n\n" + "=" * 100)
print("  FULL COMPARISON TABLE")
print("=" * 100)

metric_keys = ['Accuracy','Precision','Recall','F1 Score','ROC-AUC','MCC','Specificity','FNR','FPR']
print(f"{'Model':<25}" + "".join([f"{m:>12}" for m in metric_keys]))
print("-" * 100)

for name, metrics in baseline_results.items():
    row = f"{'  '+name:<25}"
    for m in metric_keys:
        row += f"{metrics[m]:>12.4f}"
    print(row)

print("\nBest per metric:")
for m in ['Accuracy','Recall','F1 Score','ROC-AUC','MCC']:
    best = max(baseline_results.keys(), key=lambda k: baseline_results[k][m])
    print(f"  {m:<15}: {best} ({baseline_results[best][m]:.4f})")

# ── Visualization ──
fig, ax = plt.subplots(figsize=(12, 6))

model_names  = list(baseline_results.keys())
plot_metrics = ['Accuracy','Recall','F1 Score','ROC-AUC','MCC']
colors       = ['#3498DB','#2ECC71','#E74C3C','#F39C12','#9B59B6']
x            = np.arange(len(model_names))
width        = 0.15

for i, (metric, color) in enumerate(zip(plot_metrics, colors)):
    vals = [baseline_results[m][metric] for m in model_names]
    ax.bar(x + i*width, vals, width,
           label=metric, color=color, alpha=0.85, edgecolor='white')

ax.set_xticks(x + width * 2)
ax.set_xticklabels(model_names, rotation=15, ha='right', fontsize=10)
ax.set_ylim(0, 1.15)
ax.set_ylabel('Score', fontsize=11)
ax.set_title('Baseline ML Model Comparison\n(5-Fold Cross Validation)',
             fontsize=13, fontweight='bold')
ax.legend(fontsize=9, loc='upper left')
ax.axhline(y=0.9, color='gray', linestyle='--', alpha=0.4)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.grid(axis='y', alpha=0.3)

# Highlight GCN column
gcn_idx = model_names.index('GCN (Ours)')
ax.axvspan(gcn_idx - 0.1, gcn_idx + 0.9, alpha=0.08, color='gold', label='Our GCN')

plt.tight_layout()
plt.savefig('baseline_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print("\nVisualization saved as baseline_comparison.png")

import torch
import torch.nn.functional as F
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
from torch_geometric.nn import GCNConv, global_mean_pool
from torch_geometric.data import Data
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, matthews_corrcoef, confusion_matrix
)





device     = torch.device('cpu')   # use CPU to avoid CUDA assert errors
FEATURES = [
    'age', 'sex', 'cp', 'trestbps', 'chol',
    'fbs', 'restecg', 'thalach', 'exang',
    'oldpeak', 'slope', 'ca', 'thal'
]


# ─────────────────────────────────────────────────────────────
# HELPER 1: Find best threshold on val set
# ─────────────────────────────────────────────────────────────
def find_best_threshold(model, val_graphs):
    model.to(device).eval()
    val_probs, val_true = [], []

    with torch.no_grad():
        for graph in val_graphs:
            graph = graph.to(device)
            prob  = model(graph).squeeze().item()
            val_probs.append(prob)
            val_true.append(int(graph.y.item()))

    val_probs = np.array(val_probs)
    val_true  = np.array(val_true)

    best_thresh, best_f1 = 0.5, 0
    for t in np.arange(0.10, 0.70, 0.01):
        preds = (val_probs >= t).astype(int)
        f1    = f1_score(val_true, preds, zero_division=0)
        if f1 > best_f1:
            best_f1     = f1
            best_thresh = t

    print(f"  Best threshold: {best_thresh:.2f}  F1: {best_f1:.4f}")
    return best_thresh


# ─────────────────────────────────────────────────────────────
# HELPER 2: Evaluate model
# ─────────────────────────────────────────────────────────────
def evaluate_model(model, test_graphs, threshold):
    model.to(device).eval()
    all_probs, all_preds, all_true = [], [], []

    with torch.no_grad():
        for graph in test_graphs:
            graph = graph.to(device)
            prob  = model(graph).squeeze().item()
            pred  = 1 if prob >= threshold else 0
            all_probs.append(prob)
            all_preds.append(pred)
            all_true.append(int(graph.y.item()))

    probs = np.array(all_probs)
    preds = np.array(all_preds)
    true  = np.array(all_true)

    cm = confusion_matrix(true, preds)
    TP = cm[1,1]; FN = cm[1,0]
    TN = cm[0,0]; FP = cm[0,1]

    return {
        'Accuracy':    round(accuracy_score(true, preds), 4),
        'Precision':   round(precision_score(true, preds, zero_division=0), 4),
        'Recall':      round(recall_score(true, preds, zero_division=0), 4),
        'F1 Score':    round(f1_score(true, preds, zero_division=0), 4),
        'ROC-AUC':     round(roc_auc_score(true, probs), 4),
        'MCC':         round(matthews_corrcoef(true, preds), 4),
        'Specificity': round(TN / (TN + FP), 4) if (TN + FP) > 0 else 0,
        'FNR':         round(FN / (FN + TP), 4) if (FN + TP) > 0 else 0,
        'FPR':         round(FP / (FP + TN), 4) if (FP + TN) > 0 else 0,
        'TP': int(TP), 'TN': int(TN), 'FP': int(FP), 'FN': int(FN),
    }


# ─────────────────────────────────────────────────────────────
# HELPER 3: Rebuild graph list with new edge_index
# ─────────────────────────────────────────────────────────────
def rebuild_graphs(graphs, new_edge_index):
    rebuilt = []
    for g in graphs:
        new_g            = Data()
        new_g.x          = g.x
        new_g.edge_index = new_edge_index.clone()
        new_g.y          = g.y
        rebuilt.append(new_g)
    return rebuilt


# ─────────────────────────────────────────────────────────────
# HELPER 4: Build edge_index with or without MST
# ─────────────────────────────────────────────────────────────
def build_edge_index(corr_matrix, features, use_mst=True, threshold=0.15):

    # Safety check
    assert corr_matrix.shape[0] == len(features), \
        f"Mismatch: corr_matrix has {corr_matrix.shape[0]} rows but features has {len(features)}"
    assert list(corr_matrix.columns) == features, \
        f"Column order mismatch.\nCorr: {list(corr_matrix.columns)}\nFeatures: {features}"

    G = nx.Graph()
    G.add_nodes_from(features)

    for i in range(len(features)):
        for j in range(i+1, len(features)):
            if abs(corr_matrix.iloc[i, j]) >= threshold:
                G.add_edge(features[i], features[j])

    if use_mst:
        G_complete = nx.Graph()
        for i in range(len(features)):
            for j in range(i+1, len(features)):
                G_complete.add_edge(
                    features[i], features[j],
                    weight=1 - abs(corr_matrix.iloc[i, j]))
        mst = nx.minimum_spanning_tree(G_complete)
        for u, v in mst.edges():
            if not G.has_edge(u, v):
                G.add_edge(u, v)

    node_list = list(G.nodes())
    edges     = list(G.edges())
    src = [node_list.index(u) for u,v in edges] + \
          [node_list.index(v) for u,v in edges]
    dst = [node_list.index(v) for u,v in edges] + \
          [node_list.index(u) for u,v in edges]

    return torch.tensor([src, dst], dtype=torch.long)


# ─────────────────────────────────────────────────────────────
# HELPER 5: Train any model variant
# ─────────────────────────────────────────────────────────────
def train_variant(model, train_graphs, val_graphs,
                  criterion, epochs=100, patience=15, lr=0.001):
    model.to(device)
    optimizer = torch.optim.Adam(
        model.parameters(), lr=lr, weight_decay=1e-4)

    best_val_loss = float('inf')
    best_wts      = None
    no_improve    = 0

    for epoch in range(epochs):
        model.train()
        for graph in train_graphs:
            graph = graph.to(device)
            optimizer.zero_grad()
            out  = model(graph)
            loss = criterion(out, graph.y.float())
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

        model.eval()
        val_loss, n = 0, 0
        with torch.no_grad():
            for graph in val_graphs:
                graph     = graph.to(device)
                val_loss += criterion(model(graph), graph.y.float()).item()
                n        += 1

        avg_val = val_loss / max(n, 1)

        if avg_val < best_val_loss:
            best_val_loss = avg_val
            best_wts      = {k: v.clone() for k, v in model.state_dict().items()}
            no_improve    = 0
        else:
            no_improve += 1

        if (epoch + 1) % 10 == 0:
            print(f"    Epoch [{epoch+1:>3}/{epochs}]  "
                  f"Val Loss: {avg_val:.4f}")

        if no_improve >= patience:
            print(f"    Early stopping at epoch {epoch+1}")
            break

    if best_wts:
        model.load_state_dict(best_wts)
    return model


# ─────────────────────────────────────────────────────────────
# GCN VARIANTS
# ─────────────────────────────────────────────────────────────

# Full model — with BatchNorm
class GCN_Full(torch.nn.Module):
    def __init__(self, input_channels=1, hidden_channels=32):
        super().__init__()
        self.conv1  = GCNConv(input_channels, hidden_channels)
        self.bn1    = torch.nn.BatchNorm1d(hidden_channels)
        self.conv2  = GCNConv(hidden_channels, hidden_channels)
        self.bn2    = torch.nn.BatchNorm1d(hidden_channels)
        self.linear = torch.nn.Linear(hidden_channels, 1)

    def forward(self, data):
        x, ei = data.x, data.edge_index
        x = F.relu(self.bn1(self.conv1(x, ei)))
        x = F.dropout(x, p=0.30, training=self.training)
        x = F.relu(self.bn2(self.conv2(x, ei)))
        batch = torch.zeros(x.size(0), dtype=torch.long, device=x.device)
        x = global_mean_pool(x, batch)
        return torch.sigmoid(self.linear(x)).view(-1)


# w/o BatchNorm
class GCN_NoBN(torch.nn.Module):
    def __init__(self, input_channels=1, hidden_channels=32):
        super().__init__()
        self.conv1  = GCNConv(input_channels, hidden_channels)
        self.conv2  = GCNConv(hidden_channels, hidden_channels)
        self.linear = torch.nn.Linear(hidden_channels, 1)

    def forward(self, data):
        x, ei = data.x, data.edge_index
        x = F.relu(self.conv1(x, ei))
        x = F.dropout(x, p=0.30, training=self.training)
        x = F.relu(self.conv2(x, ei))
        batch = torch.zeros(x.size(0), dtype=torch.long, device=x.device)
        x = global_mean_pool(x, batch)
        return torch.sigmoid(self.linear(x)).view(-1)


# ─────────────────────────────────────────────────────────────
# LOSS FUNCTIONS
# Cleveland is nearly balanced (~165:138) → pos_weight ~1.19
# ─────────────────────────────────────────────────────────────
criterion_balanced = torch.nn.BCELoss()          # standard balanced
criterion_plain    = torch.nn.BCELoss()          # same — no pos_weight variant


# ─────────────────────────────────────────────────────────────
# RUN ALL 5 VARIANTS
# Requires from your notebook:
#   model        → your trained full GCN (already on device)
#   train_graphs, val_graphs, test_graphs
#   corr_matrix  → pd.DataFrame of Pearson correlations
# ─────────────────────────────────────────────────────────────
print("=" * 60)
print("  ABLATION STUDY — CLEVELAND DATASET")
print("=" * 60)

# ── Variant 1: Full Model ──
print("\n[1/5] Full Model (Ours)")
model.to(device)
thresh_full  = find_best_threshold(model, val_graphs)
results_full = evaluate_model(model, test_graphs, thresh_full)
print(f"  Recall: {results_full['Recall']}  "
      f"F1: {results_full['F1 Score']}  "
      f"AUC: {results_full['ROC-AUC']}  "
      f"MCC: {results_full['MCC']}")

# ── Variant 2: w/o MST Bridges ──
print("\n[2/5] w/o MST Bridges")
ei_no_mst      = build_edge_index(corr_matrix, FEATURES, use_mst=False)
train_no_mst   = rebuild_graphs(train_graphs, ei_no_mst)
val_no_mst     = rebuild_graphs(val_graphs,   ei_no_mst)
test_no_mst    = rebuild_graphs(test_graphs,  ei_no_mst)
model_no_mst   = GCN_Full(1, 32)
model_no_mst   = train_variant(model_no_mst, train_no_mst,
                                val_no_mst, criterion_balanced)
thresh_no_mst  = find_best_threshold(model_no_mst, val_no_mst)
results_no_mst = evaluate_model(model_no_mst, test_no_mst, thresh_no_mst)
print(f"  Recall: {results_no_mst['Recall']}  "
      f"F1: {results_no_mst['F1 Score']}  "
      f"AUC: {results_no_mst['ROC-AUC']}  "
      f"MCC: {results_no_mst['MCC']}")

# ── Variant 3: w/o BatchNorm ──
print("\n[3/5] w/o BatchNorm")
model_no_bn   = GCN_NoBN(1, 32)
model_no_bn   = train_variant(model_no_bn, train_graphs,
                               val_graphs, criterion_balanced)
thresh_no_bn  = find_best_threshold(model_no_bn, val_graphs)
results_no_bn = evaluate_model(model_no_bn, test_graphs, thresh_no_bn)
print(f"  Recall: {results_no_bn['Recall']}  "
      f"F1: {results_no_bn['F1 Score']}  "
      f"AUC: {results_no_bn['ROC-AUC']}  "
      f"MCC: {results_no_bn['MCC']}")

# ── Variant 4: w/o Threshold Tuning (fixed 0.5) ──
print("\n[4/5] w/o Threshold Tuning")
results_no_thresh = evaluate_model(model, test_graphs, 0.5)
print(f"  Recall: {results_no_thresh['Recall']}  "
      f"F1: {results_no_thresh['F1 Score']}  "
      f"AUC: {results_no_thresh['ROC-AUC']}  "
      f"MCC: {results_no_thresh['MCC']}")

# ── Variant 5: w/o pos_weight (retrain fresh) ──
print("\n[5/5] w/o pos_weight")
model_no_pw   = GCN_Full(1, 32)
model_no_pw   = train_variant(model_no_pw, train_graphs,
                               val_graphs, criterion_plain)
thresh_no_pw  = find_best_threshold(model_no_pw, val_graphs)
results_no_pw = evaluate_model(model_no_pw, test_graphs, thresh_no_pw)
print(f"  Recall: {results_no_pw['Recall']}  "
      f"F1: {results_no_pw['F1 Score']}  "
      f"AUC: {results_no_pw['ROC-AUC']}  "
      f"MCC: {results_no_pw['MCC']}")


# ─────────────────────────────────────────────────────────────
# FINAL TABLE + DELTA
# ─────────────────────────────────────────────────────────────
ablation_results = {
    'Full Model (Ours)':    results_full,
    'w/o MST Bridges':      results_no_mst,
    'w/o BatchNorm':        results_no_bn,
    'w/o Threshold Tuning': results_no_thresh,
    'w/o pos_weight':       results_no_pw,
}

keys = ['Accuracy', 'Recall', 'F1 Score', 'ROC-AUC', 'MCC', 'FNR']

print("\n\n" + "=" * 76)
print("  COMPLETE ABLATION STUDY TABLE")
print("=" * 76)
print(f"{'Variant':<28}" + "".join([f"{k:>12}" for k in keys]))
print("-" * 76)
for variant, metrics in ablation_results.items():
    row = f"{'  '+variant:<28}"
    for k in keys:
        row += f"{metrics[k]:>12.4f}"
    print(row)

print("\nDelta from Full Model:")
full = ablation_results['Full Model (Ours)']
print(f"{'Variant':<28}" + "".join([f"{k:>12}" for k in keys]))
print("-" * 76)
for variant, metrics in ablation_results.items():
    if variant == 'Full Model (Ours)':
        continue
    row = f"{'  '+variant:<28}"
    for k in keys:
        row += f"{metrics[k] - full[k]:>+12.4f}"
    print(row)


# ─────────────────────────────────────────────────────────────
# VISUALIZATION
# ─────────────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(14, 6))

names      = list(ablation_results.keys())
ab_metrics = ['Recall', 'F1 Score', 'ROC-AUC', 'MCC']
ab_colors  = ['#E74C3C', '#2ECC71', '#3498DB', '#F39C12']
x          = np.arange(len(names))
width      = 0.18

for i, (metric, color) in enumerate(zip(ab_metrics, ab_colors)):
    vals = [ablation_results[n][metric] for n in names]
    bars = ax.bar(x + i*width, vals, width,
                  label=metric, color=color, alpha=0.85, edgecolor='white')
    for bar, val in zip(bars, vals):
        ax.text(bar.get_x() + bar.get_width()/2,
                bar.get_height() + 0.01,
                f'{val:.3f}', ha='center', va='bottom', fontsize=6.5)

ax.set_xticks(x + width * 1.5)
ax.set_xticklabels(
    [n.replace('w/o ', 'w/o\n') for n in names],
    ha='center', fontsize=9)
ax.set_ylim(0, 1.20)
ax.set_ylabel('Score', fontsize=11)
ax.set_title('Ablation Study — Component Contribution Analysis\n'
             '(Cleveland Heart Disease Dataset)',
             fontsize=13, fontweight='bold')
ax.legend(fontsize=9)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.grid(axis='y', alpha=0.3)
ax.axvspan(-0.3, 0.9, alpha=0.08, color='gold')

plt.tight_layout()
plt.savefig('ablation_study.png', dpi=150, bbox_inches='tight')
plt.show()
print("\nSaved: ablation_study.png")

"""**Graph Centrality Analysis**"""



"""Degree centrality was computed to identify influential risk factors.
CD(v)=deg(v)/ n−1

"""

n = G.number_of_nodes()

print("Degree centrality \n\n")

degree_centrality = {}

for node in G.nodes():

    degree = G.degree(node)

    centrality = degree / (n-1)

    degree_centrality[node] = centrality

centrality_df = pd.DataFrame(
    degree_centrality.items(),
    columns=["Feature", "Centrality"]
)

centrality_df = centrality_df.sort_values(
    "Centrality",
    ascending=False
)

print(centrality_df)

top_feature = centrality_df.iloc[0]["Feature"]
top_score = centrality_df.iloc[0]["Centrality"]

print("\nINTERPRETATION")
print(
    f"• {top_feature} acted as the dominant hub connecting "
    f"multiple cardiovascular variables "
    f"(Degree Centrality = {top_score:.3f}).")

"""**Spectral Analysis**"""

G_abs = nx.Graph()
for u, v, d in G.edges(data=True):
    G_abs.add_edge(u, v, weight=abs(d['weight']))
L = nx.laplacian_matrix(G_abs, weight='weight').toarray()
eigenvalues = np.sort(np.linalg.eigvalsh(L))
fiedler = eigenvalues[1]



num_components = np.sum(
    np.isclose(eigenvalues, 0, atol=1e-6)
)

centrality = nx.degree_centrality(G)

top_nodes = sorted(
    centrality.items(),
    key=lambda x: x[1],
    reverse=True
)[:3]

print("Connected Components:", num_components)
print("Top Nodes:", top_nodes)

print("\nSPECTRAL ANALYSIS INFERENCE")

if num_components == 1:
    print("• One large connected medical component")

print(
    f"• {top_nodes[0][0]} and "
    f"{top_nodes[1][0]} positioned as dominant cluster nodes"
)

"""**Explainability Generation**

*feature_scores = weights * patient_features*
"""

import torch
import torch.nn.functional as F
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from torch_geometric.explain import Explainer, GNNExplainer
from torch_geometric.data import Data

DEVICE       = torch.device('cpu')
TOP_K        = 5
FEATURES     = [
    'age', 'sex', 'cp', 'trestbps', 'chol',
    'fbs', 'restecg', 'thalach', 'exang',
    'oldpeak', 'slope', 'ca', 'thal'
]
CLINICAL_TOP = [
    'age', 'trestbps', 'chol', 'thalach',
    'exang', 'oldpeak', 'ca', 'cp', 'thal'
]
N_FEATURES   = len(FEATURES)  # 13


# ─────────────────────────────────────────────────────────────
# Safe weight extraction — works for all PyG versions
# ─────────────────────────────────────────────────────────────
def get_conv1_weight(model):
    """
    GCNConv weight attribute varies by PyG version:
      Newer PyG : model.conv1.lin.weight   -> shape [hidden, in]
      Older PyG : model.conv1.weight       -> shape [hidden, in]
    This function handles both safely.
    """
    conv1 = model.conv1
    if hasattr(conv1, 'lin') and hasattr(conv1.lin, 'weight'):
        return conv1.lin.weight.detach().cpu().numpy()   # newer PyG
    elif hasattr(conv1, 'weight'):
        return conv1.weight.detach().cpu().numpy()       # older PyG
    else:
        # Fallback: use final linear layer weights
        return model.linear.weight.detach().cpu().numpy()


# ─────────────────────────────────────────────────────────────
# GNNExplainer WRAPPER
# ─────────────────────────────────────────────────────────────
class GNNExplainerWrapper(torch.nn.Module):
    def __init__(self, model):
        super().__init__()
        self.model = model

    def forward(self, x, edge_index):
        data       = Data(x=x, edge_index=edge_index)
        data.batch = torch.zeros(
            x.size(0), dtype=torch.long, device=x.device)
        return self.model(data)


# ─────────────────────────────────────────────────────────────
# BASELINE XAI: Ii = wi x xi
# ─────────────────────────────────────────────────────────────
def baseline_explanation(model, graph):
    model.to(DEVICE).eval()
    graph = graph.to(DEVICE)
    with torch.no_grad():
        w      = get_conv1_weight(model)       # [hidden, input]
        w      = np.abs(w).mean(axis=0)        # [input_channels]
        x      = graph.x.cpu().numpy().flatten()  # [N_FEATURES]

        # w[0] because input_channels=1 (each node has 1 feature)
        scores = float(w[0]) * np.abs(x)
        scores = scores / (scores.sum() + 1e-8)
    return scores  # [N_FEATURES]


# ─────────────────────────────────────────────────────────────
# GNNExplainer XAI
# ─────────────────────────────────────────────────────────────
def gnnexplainer_explanation(model, graph):
    model.to(DEVICE).eval()
    graph         = graph.to(DEVICE)
    wrapped_model = GNNExplainerWrapper(model).to(DEVICE)
    wrapped_model.eval()

    explainer = Explainer(
        model=wrapped_model,
        algorithm=GNNExplainer(epochs=100),
        explanation_type='model',
        node_mask_type='attributes',
        edge_mask_type='object',
        model_config=dict(
            mode='binary_classification',
            task_level='graph',
            return_type='probs',
        ),
    )
    explanation = explainer(graph.x, graph.edge_index)
    scores      = explanation.node_mask.cpu().numpy().flatten()
    scores      = scores / (scores.sum() + 1e-8)
    return scores  # [N_FEATURES]


# ─────────────────────────────────────────────────────────────
# XAI METRICS
# ─────────────────────────────────────────────────────────────

# FIX #1: Fidelity — larger prediction change when top-k features are
# masked means the explainer correctly identified influential features.
# The old code returned 1 - |change|, which rewarded explanations that
# picked UNimportant features (no change when masked). Now we return
# |change| directly: bigger drop = better explanation.
def compute_fidelity(model, graph, feature_scores, top_k=TOP_K):
    model.to(DEVICE).eval()
    graph = graph.to(DEVICE)
    with torch.no_grad():
        original_prob = model(graph).squeeze().item()
        top_indices   = np.argsort(feature_scores)[-top_k:]
        x_masked      = graph.x.clone()
        x_masked[top_indices] = 0.0
        g_masked      = graph.clone()
        g_masked.x    = x_masked
        masked_prob   = model(g_masked).squeeze().item()
    return abs(original_prob - masked_prob)  # larger drop = better


# FIX #2: Sparsity — standard convention is
# 1 - (selected_features / total_features), so a MORE concentrated
# (sparser) explanation scores HIGHER, consistent with every other
# metric here where higher = better.
def compute_sparsity(feature_scores, top_k=TOP_K):
    threshold  = np.mean(feature_scores)
    k_selected = np.sum(feature_scores > threshold)
    return 1.0 - (k_selected / N_FEATURES)


def compute_stability(model, graph, explain_fn, n_trials=5, noise_std=0.01):
    graph    = graph.to(DEVICE)
    original = explain_fn(model, graph)
    devs     = []
    for _ in range(n_trials):
        x_noisy   = graph.x + torch.randn_like(graph.x) * noise_std
        g_noisy   = graph.clone()
        g_noisy.x = x_noisy
        devs.append(np.mean(np.abs(explain_fn(model, g_noisy) - original)))
    return max(0.0, 1.0 - np.mean(devs))


def compute_fia(feature_scores, top_k=TOP_K):
    top_idx  = np.argsort(feature_scores)[-top_k:]
    top_feat = [FEATURES[i] for i in top_idx]
    matches  = len(set(top_feat) & set(CLINICAL_TOP))
    return matches / top_k, top_feat


def compute_crs(feature_scores, top_k=TOP_K):
    top_idx  = np.argsort(feature_scores)[-top_k:]
    top_feat = [FEATURES[i] for i in top_idx]
    return sum(1 for f in top_feat if f in CLINICAL_TOP) / len(top_feat)


def compute_coverage(model, graphs, explain_fn):
    valid = 0
    for g in graphs:
        try:
            s = explain_fn(model, g.to(DEVICE))
            if s is not None and len(s) == N_FEATURES:
                valid += 1
        except:
            pass
    return valid / len(graphs)


# ─────────────────────────────────────────────────────────────
# MAIN EVALUATION
# ─────────────────────────────────────────────────────────────
def evaluate_xai(model, test_graphs, n_samples=30):
    model.to(DEVICE)
    samples = test_graphs[:n_samples]
    res = {
        'Baseline':    {k:[] for k in ['fidelity','sparsity','stability','fia','crs']},
        'GNNExplainer':{k:[] for k in ['fidelity','sparsity','stability','fia','crs']},
    }

    print(f"Computing XAI metrics on {n_samples} samples...")
    print("-" * 50)

    for i, graph in enumerate(samples):
        graph = graph.to(DEVICE)
        if (i+1) % 5 == 0:
            print(f"  Sample {i+1}/{n_samples}...")

        # -- Baseline --
        try:
            b = baseline_explanation(model, graph)
            res['Baseline']['fidelity'].append(compute_fidelity(model, graph, b))
            res['Baseline']['sparsity'].append(compute_sparsity(b))
            res['Baseline']['stability'].append(
                compute_stability(model, graph, baseline_explanation))
            fia, _ = compute_fia(b)
            res['Baseline']['fia'].append(fia)
            res['Baseline']['crs'].append(compute_crs(b))
        except Exception as e:
            print(f"  Baseline error sample {i}: {e}")

        # -- GNNExplainer --
        try:
            g = gnnexplainer_explanation(model, graph)
            res['GNNExplainer']['fidelity'].append(compute_fidelity(model, graph, g))
            res['GNNExplainer']['sparsity'].append(compute_sparsity(g))
            res['GNNExplainer']['stability'].append(
                compute_stability(model, graph, gnnexplainer_explanation))
            fia, _ = compute_fia(g)
            res['GNNExplainer']['fia'].append(fia)
            res['GNNExplainer']['crs'].append(compute_crs(g))
        except Exception as e:
            print(f"  GNNExplainer error sample {i}: {e}")

    b_cov = compute_coverage(model, samples, baseline_explanation)
    g_cov = compute_coverage(model, samples, gnnexplainer_explanation)

    def avg(lst): return round(np.mean(lst), 4) if lst else 0.0

    b_fid,b_spa,b_sta = avg(res['Baseline']['fidelity']),avg(res['Baseline']['sparsity']),avg(res['Baseline']['stability'])
    b_fia,b_crs       = avg(res['Baseline']['fia']),avg(res['Baseline']['crs'])
    b_ti              = round((b_fid+b_sta+b_crs)/3, 4)

    g_fid,g_spa,g_sta = avg(res['GNNExplainer']['fidelity']),avg(res['GNNExplainer']['sparsity']),avg(res['GNNExplainer']['stability'])
    g_fia,g_crs       = avg(res['GNNExplainer']['fia']),avg(res['GNNExplainer']['crs'])
    g_ti              = round((g_fid+g_sta+g_crs)/3, 4)

    names  = ['Fidelity','Sparsity','Stability',
              'Feature Importance Accuracy','Clinical Relevance Score',
              'Explanation Coverage','Trustworthiness Index']
    b_vals = [b_fid,b_spa,b_sta,b_fia,b_crs,round(b_cov,4),b_ti]
    g_vals = [g_fid,g_spa,g_sta,g_fia,g_crs,round(g_cov,4),g_ti]

    # FIX #3: sparsity now follows "higher = better" like every other
    # metric, so the special-cased comparison for index 1 is removed.
    winners = ['GNNExplainer' if g > b else 'Baseline' for b, g in zip(b_vals, g_vals)]

    df = pd.DataFrame({'Metric':names,'Baseline':b_vals,
                       'GNNExplainer':g_vals,'Better Method':winners})

    print("\n"+"="*70)
    print("  XAI COMPARISON: Baseline vs GNNExplainer")
    print("="*70)
    print(f"\n{'Metric':<30} {'Baseline':>10} {'GNNExplainer':>14} {'Winner':>14}")
    print("-"*70)
    for _,row in df.iterrows():
        print(f"  {row['Metric']:<28} {row['Baseline']:>10.4f} "
              f"{row['GNNExplainer']:>14.4f} {row['Better Method']:>14}")

    return df, res


# ─────────────────────────────────────────────────────────────
# VISUALIZATION
# ─────────────────────────────────────────────────────────────
def plot_xai_comparison(df):
    metrics  = df['Metric'].tolist()
    baseline = df['Baseline'].tolist()
    gnnexp   = df['GNNExplainer'].tolist()
    x        = np.arange(len(metrics))
    width    = 0.35

    fig, axes = plt.subplots(1, 2, figsize=(18, 7))
    ax        = axes[0]

    bars1 = ax.bar(x-width/2, baseline, width, label='Baseline (wixi)',
                   color='#E74C3C', alpha=0.85, edgecolor='white')
    bars2 = ax.bar(x+width/2, gnnexp,   width, label='GNNExplainer',
                   color='#2ECC71', alpha=0.85, edgecolor='white')

    for bar in bars1:
        ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.01,
                f'{bar.get_height():.3f}', ha='center', va='bottom',
                fontsize=7.5, fontweight='bold')
    for bar in bars2:
        ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.01,
                f'{bar.get_height():.3f}', ha='center', va='bottom',
                fontsize=7.5, fontweight='bold', color='#1A7A40')

    ax.set_xticks(x)
    ax.set_xticklabels([m.replace(' ','\n') for m in metrics], fontsize=8)
    ax.set_ylim(0, 1.15)
    ax.set_ylabel('Score', fontsize=11)
    ax.set_title('XAI Metric Comparison\nBaseline vs GNNExplainer\n'
                 '(Cleveland Heart Disease Dataset)',
                 fontsize=12, fontweight='bold')
    ax.legend(fontsize=10)
    ax.axhline(y=0.7, color='gray', linestyle='--', alpha=0.5)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.grid(axis='y', alpha=0.3)

    # FIX #4: sparsity is no longer inverted here since compute_sparsity
    # now already returns "higher = better" directly.
    radar_labels   = ['Fidelity','Sparsity','Stability','FIA','CRS','TI']
    radar_baseline = [baseline[0],baseline[1],baseline[2],baseline[3],baseline[4],baseline[6]]
    radar_gnnexp   = [gnnexp[0],  gnnexp[1],  gnnexp[2],  gnnexp[3],  gnnexp[4],  gnnexp[6]]
    angles         = np.linspace(0,2*np.pi,len(radar_labels),endpoint=False).tolist()
    angles        += angles[:1]
    radar_baseline += radar_baseline[:1]
    radar_gnnexp   += radar_gnnexp[:1]

    ax2 = plt.subplot(122, polar=True)
    ax2.plot(angles, radar_baseline, 'o-', lw=2, color='#E74C3C', label='Baseline')
    ax2.fill(angles, radar_baseline, alpha=0.15, color='#E74C3C')
    ax2.plot(angles, radar_gnnexp,   'o-', lw=2, color='#2ECC71', label='GNNExplainer')
    ax2.fill(angles, radar_gnnexp,   alpha=0.15, color='#2ECC71')
    ax2.set_xticks(angles[:-1])
    ax2.set_xticklabels(radar_labels, fontsize=9)
    ax2.set_ylim(0, 1)
    ax2.set_yticks([0.2,0.4,0.6,0.8,1.0])
    ax2.set_yticklabels(['0.2','0.4','0.6','0.8','1.0'], fontsize=7)
    ax2.set_title('XAI Radar Chart', fontsize=12, fontweight='bold', pad=20)
    ax2.legend(loc='upper right', bbox_to_anchor=(1.3,1.1), fontsize=10)
    ax2.grid(True, alpha=0.3)

    plt.tight_layout(pad=2)
    plt.savefig('xai_comparison.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("Saved: xai_comparison.png")


# ─────────────────────────────────────────────────────────────
# PATIENT EXPLANATION PLOT
# ─────────────────────────────────────────────────────────────
def plot_sample_explanation(model, graph, sample_idx=0):
    model.to(DEVICE)
    graph     = graph.to(DEVICE)
    b_scores  = baseline_explanation(model, graph)
    g_scores  = gnnexplainer_explanation(model, graph)
    label_str = "Disease" if int(graph.y.view(-1).item())==1 else "No Disease"

    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    for ax, scores, title, color in zip(
        axes,
        [b_scores, g_scores],
        [f'Baseline\nSample #{sample_idx} | Label: {label_str}',
         f'GNNExplainer\nSample #{sample_idx} | Label: {label_str}'],
        ['#E74C3C', '#2ECC71']
    ):
        sorted_idx  = np.argsort(scores)
        sorted_feat = [FEATURES[i] for i in sorted_idx]
        sorted_vals = scores[sorted_idx]
        bars = ax.barh(range(N_FEATURES), sorted_vals,
                       color=color, alpha=0.8, edgecolor='white')
        ax.set_yticks(range(N_FEATURES))
        ax.set_yticklabels(sorted_feat, fontsize=9)
        ax.set_xlabel('Influence Score (normalized)', fontsize=10)
        ax.set_title(title, fontsize=12, fontweight='bold')
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)
        for i,(bar,val) in enumerate(zip(bars,sorted_vals)):
            ax.text(val+0.002, i, f'{val:.3f}', va='center', fontsize=8)

    plt.tight_layout()
    plt.savefig(f'explanation_sample_{sample_idx}.png', dpi=150, bbox_inches='tight')
    plt.show()
    print(f"Saved: explanation_sample_{sample_idx}.png")


# ─────────────────────────────────────────────────────────────
# RUN
# ─────────────────────────────────────────────────────────────
model.to(DEVICE)

df_results, raw = evaluate_xai(model, test_graphs, n_samples=30)
plot_xai_comparison(df_results)

disease_graphs = [g for g in test_graphs if g.y.view(-1).item()==1]
if disease_graphs:
    plot_sample_explanation(model, disease_graphs[0], sample_idx=0)

df_results.to_csv('xai_comparison_results.csv', index=False)
print("\nSaved: xai_comparison_results.csv")

